# Generated by Django 3.2 on 2023-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioCapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_id', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('serie', models.CharField(blank=True, max_length=255, null=True)),
                ('folio', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('folio_a', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_a', models.DateTimeField()),
                ('importe_flete', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cant_a', models.DecimalField(decimal_places=3, max_digits=19)),
                ('costo_unitario', models.DecimalField(decimal_places=3, max_digits=19)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=19)),
                ('inventario_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.BigIntegerField()),
                ('clave', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('nacional', models.BooleanField(default=False)),
                ('unidad', models.CharField(max_length=255)),
                ('kilos', models.DecimalField(decimal_places=3, max_digits=19)),
                ('disponible', models.DecimalField(decimal_places=3, max_digits=19)),
                ('disponible_acumulado', models.DecimalField(decimal_places=3, max_digits=19)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=19)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('costo_promedio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('cantidad_original', models.DecimalField(decimal_places=3, max_digits=19)),
                ('ejercicio', models.BigIntegerField()),
                ('mes', models.BigIntegerField()),
                ('partidas_idx', models.IntegerField(blank=True, null=True)),
                ('version', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventario_capas',
                'managed': False,
            },
        ),
    ]
