# Generated by Django 3.2 on 2023-06-15 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('gramos', models.DecimalField(decimal_places=2, max_digits=19)),
                ('inventariable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
    ]
