# Generated by Django 3.2 on 2023-05-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactVentasDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3)),
                ('origen_id', models.CharField(max_length=255)),
                ('inventario_id', models.CharField(max_length=255)),
                ('cliente_id', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('docto', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=3)),
                ('sucursal_id', models.CharField(max_length=255)),
                ('suc', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('linea_id', models.CharField(max_length=255)),
                ('linea', models.CharField(max_length=30)),
                ('marca_id', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=30)),
                ('clase_id', models.CharField(max_length=255)),
                ('clase', models.CharField(max_length=30)),
                ('producto_id', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=3)),
                ('factoru', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('gramos', models.IntegerField(default=0)),
                ('kxmil', models.CharField(max_length=255)),
                ('calibre', models.IntegerField(default=0)),
                ('caras', models.IntegerField(default=0)),
                ('delinea', models.BooleanField(default=True)),
                ('nacional', models.BooleanField(default=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('kilos', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('precio_l', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('imp_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('dscto_esp', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('cortes', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('precio_cortes', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('imp_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('costop', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('descto_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('rebate', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('costo_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('semana', models.IntegerField(default=0)),
                ('ejercicio', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'analisis_ventas_det',
                'managed': True,
            },
        ),
    ]
