# Generated by Django 3.2 on 2023-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_ventas', '0002_rename_factventasdet_analisisventasdet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobrePrecioImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'sobreprecio_importacion',
                'managed': True,
            },
        ),
    ]
