# Generated by Django 3.2 on 2023-05-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_ventas', '0004_existencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Existencia',
        ),
    ]
