from rest_framework import serializers
from ..models import  AnalisisVentasDet

class AnalisisVentaSerializer(serializers.Serializer):
    subdimension = serializers.CharField(max_length = 255)
    ejercicio = serializers.IntegerField()
    mes = serializers.IntegerField()
    sum_importe = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_imp_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    porcentaje_utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    precio_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_vn = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_ut = serializers.DecimalField( max_digits=18, decimal_places=2)
    descripcion = serializers.CharField(max_length = 255)
 
    

class ProyeccionInventarioSerializer(serializers.Serializer):
    subdimension = serializers.CharField(max_length = 255)
    ejercicio = serializers.IntegerField()
    mes = serializers.IntegerField()
    sum_importe = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_porc = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_imp_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    porcentaje_utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_cantidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    precio_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    costo_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_vn = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_ut = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_precio_venta = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_venta = serializers.DecimalField( max_digits=18, decimal_places=2)
    kilos_millar = serializers.DecimalField( max_digits=18, decimal_places=2)
    linea = serializers.CharField(max_length = 255)
    marca = serializers.CharField(max_length = 255)
    clase = serializers.CharField(max_length = 255)
    existencia = serializers.DecimalField( max_digits=18, decimal_places=2)
            

class AnalisisModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = AnalisisVentasDet
        fields =['origen_id','cliente','tipo','docto','fecha','clave','descripcion','imp_neto','origen','suc','kilos','costo']
        #fields ="__all__"

class ProyeccionCostoSerializer(serializers.Serializer):
    subdimension = serializers.CharField(max_length = 255)
    ejercicio = serializers.IntegerField()
    mes = serializers.IntegerField()
    sum_importe = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_porc = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_imp_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    porcentaje_utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    precio_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    costo_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_vn = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_ut = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    descripcion = serializers.CharField(max_length = 255)


class ProyeccionCostoAcumuladoSerializer(serializers.Serializer):
    subdimension = serializers.CharField(max_length = 255)
    ejercicio = serializers.IntegerField()
    sum_importe = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_porc = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_imp_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    porcentaje_utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    precio_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    costo_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_vn = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_ut = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    descripcion = serializers.CharField(max_length = 255)


class ProyeccionInventarioAcumuladoSerializer(serializers.Serializer):
    subdimension = serializers.CharField(max_length = 255)
    ejercicio = serializers.IntegerField()
    sum_importe = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_porc = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_imp_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_neto = serializers.DecimalField( max_digits=18, decimal_places=2)
    utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    porcentaje_utilidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_cantidad = serializers.DecimalField( max_digits=18, decimal_places=2)
    precio_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    costo_kilo = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_vn = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_ut = serializers.DecimalField( max_digits=18, decimal_places=2)
    porc_part_kilos = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_precio_venta = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_venta = serializers.DecimalField( max_digits=18, decimal_places=2)
    kilos_millar = serializers.DecimalField( max_digits=18, decimal_places=2)
    linea = serializers.CharField(max_length = 255)
    marca = serializers.CharField(max_length = 255)
    clase = serializers.CharField(max_length = 255)
    existencia = serializers.DecimalField( max_digits=18, decimal_places=2)


class ComparativoSerializer(serializers.Serializer):
    dimension = serializers.CharField(max_length = 255)
    ejercicio_x = serializers.IntegerField()
    sum_importe_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_porc_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_imp_neto_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_neto_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    utilidad_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    porcentaje_utilidad_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_kilos_x = serializers.DecimalField( max_digits=18, decimal_places=3)
    sum_cantidad_x = serializers.DecimalField( max_digits=18, decimal_places=3)
    precio_kilo_x = serializers.DecimalField( max_digits=18, decimal_places=2)
    mes_i_x = serializers.IntegerField()
    mes_f_x = serializers.IntegerField() 
    ejercicio_y = serializers.IntegerField()
    sum_importe_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_descuento_porc_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_imp_neto_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_costo_neto_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    utilidad_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    porcentaje_utilidad_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    sum_kilos_y = serializers.DecimalField( max_digits=18, decimal_places=3)
    sum_cantidad_y = serializers.DecimalField( max_digits=18, decimal_places=3)
    precio_kilo_y = serializers.DecimalField( max_digits=18, decimal_places=2)
    diferencia_toneladas= serializers.DecimalField( max_digits=18, decimal_places=2)
    diferencia_ventas= serializers.DecimalField( max_digits=18, decimal_places=2)
    diferencia_margen= serializers.DecimalField( max_digits=18, decimal_places=2)
    diferencia_porcentaje_margen= serializers.DecimalField( max_digits=18, decimal_places=2)
    diferencia_precio_kilo= serializers.DecimalField( max_digits=18, decimal_places=2)
    mes_i_y = serializers.IntegerField()
    mes_f_y = serializers.IntegerField() 

